cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "SPIR-V embedding requires OUTPUT")
endif()
set(header "#pragma once\n#include <array>\n#include <cstdint>\nnamespace pusu::vk_shaders {\n")
foreach(name material_vertex material_fragment material_ray_fragment fullscreen_vertex post_fragment history_fragment)
    string(TOUPPER "${name}" variable)
    if(NOT DEFINED ${variable})
        message(FATAL_ERROR "Missing SPIR-V input ${variable}")
    endif()
    file(READ "${${variable}}" bytes HEX)
    string(LENGTH "${bytes}" length)
    math(EXPR remainder "${length} % 8")
    if(length LESS 40 OR NOT remainder EQUAL 0)
        message(FATAL_ERROR "Invalid SPIR-V word storage: ${${variable}}")
    endif()
    string(SUBSTRING "${bytes}" 0 8 magic)
    if(NOT magic STREQUAL "03022307")
        message(FATAL_ERROR "Expected little-endian SPIR-V: ${${variable}}")
    endif()
    math(EXPR count "${length} / 8")
    string(APPEND header "inline constexpr std::array<std::uint32_t,${count}> ${name}_spv{\n")
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u,\n" words "${bytes}")
    string(APPEND header "${words}};\n")
endforeach()
string(APPEND header "} // namespace pusu::vk_shaders\n")
file(WRITE "${OUTPUT}.pending" "${header}")
file(RENAME "${OUTPUT}.pending" "${OUTPUT}")
